sudo: required
services:
  - docker

before_install:
  - docker build -t bnpavlov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bnpavlov/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "web-app-docker"
  env: "Web-app-docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-571532918022"
  bucket_path: "web-app-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"